"""
agents/rag_agent.py
--------------------
10-K RAG Agent for Argus.

Responsibility:
  - Auto-download the most recent 10-K filing from SEC EDGAR for the ticker
  - Chunk and embed the PDF locally using sentence-transformers
  - Store in an ephemeral ChromaDB collection (per session, no persistence)
  - Answer each question in session.filing_questions using retrieval + Gemini
  - Write results into ResearchSession

Input (reads from session):
  - session.ticker
  - session.filing_questions  (generated by orchestrator based on sentiment themes)

Output (writes to session):
  - session.filing_path
  - session.filing_year
  - session.rag_answers  (list of RAGAnswer objects)
"""

import os
import json
import requests
import time
import google.generativeai as genai
import chromadb
from chromadb.config import Settings
from langchain_community.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer

from core.session import ResearchSession, RAGAnswer
from config import (
    GEMINI_API_KEY,
    GEMINI_MODEL,
    DATA_DIR,
    CHUNK_SIZE,
    CHUNK_OVERLAP,
    RAG_TOP_K,
    EMBEDDING_MODEL,
    EDGAR_BASE_URL,
    EDGAR_FILING_URL,
    EDGAR_HEADERS,
    ORCHESTRATOR_TEMPERATURE,
)

genai.configure(api_key=GEMINI_API_KEY)

# Load embedding model once at module level (avoids reloading per session)
print("  [rag_agent] Loading embedding model (first run may take a moment)...")
_embedder = SentenceTransformer(EMBEDDING_MODEL)


# ─── SEC EDGAR Download ────────────────────────────────────────────────────────

def _get_cik(ticker: str) -> str | None:
    """Resolve ticker to SEC CIK number."""
    url = f"https://efts.sec.gov/LATEST/search-index?q=%22{ticker}%22&forms=10-K"
    try:
        resp = requests.get(
            f"https://data.sec.gov/submissions/CIK{{}}.json",
            headers=EDGAR_HEADERS,
            timeout=10,
        )
    except Exception:
        pass

    # Use the ticker-to-CIK mapping endpoint
    try:
        resp = requests.get(
            "https://www.sec.gov/files/company_tickers.json",
            headers=EDGAR_HEADERS,
            timeout=10,
        )
        data = resp.json()
        for entry in data.values():
            if entry.get("ticker", "").upper() == ticker.upper():
                cik = str(entry["cik_str"]).zfill(10)
                return cik
    except Exception as e:
        print(f"  [rag_agent] CIK lookup failed: {e}")
    return None


def _get_latest_10k_url(cik: str) -> tuple[str, str] | tuple[None, None]:
    """
    Given a CIK, find the most recent 10-K filing and return
    (document_url, filing_year).
    """
    submissions_url = f"https://data.sec.gov/submissions/CIK{cik}.json"
    try:
        resp = requests.get(submissions_url, headers=EDGAR_HEADERS, timeout=15)
        data = resp.json()
    except Exception as e:
        print(f"  [rag_agent] Submissions fetch failed: {e}")
        return None, None

    filings = data.get("filings", {}).get("recent", {})
    forms = filings.get("form", [])
    accession_numbers = filings.get("accessionNumber", [])
    dates = filings.get("filingDate", [])
    primary_docs = filings.get("primaryDocument", [])

    for i, form in enumerate(forms):
        if form == "10-K":
            accession = accession_numbers[i].replace("-", "")
            primary_doc = primary_docs[i]
            filing_date = dates[i]
            filing_year = filing_date[:4]

            doc_url = (
                f"{EDGAR_FILING_URL}/Archives/edgar/data/"
                f"{int(cik)}/{accession}/{primary_doc}"
            )
            return doc_url, filing_year

    return None, None


def _download_10k(ticker: str) -> tuple[str, str] | tuple[None, None]:
    """
    Download the most recent 10-K PDF for the ticker.
    Returns (local_file_path, filing_year).
    """
    os.makedirs(DATA_DIR, exist_ok=True)

    print(f"  [rag_agent] Resolving CIK for {ticker}...")
    cik = _get_cik(ticker)
    if not cik:
        print(f"  [rag_agent] Could not resolve CIK for {ticker}")
        return None, None

    print(f"  [rag_agent] CIK: {cik}. Fetching latest 10-K filing...")
    doc_url, filing_year = _get_latest_10k_url(cik)
    if not doc_url:
        print(f"  [rag_agent] No 10-K found for {ticker}")
        return None, None

    # Check if already downloaded (avoid re-downloading on repeated runs)
    local_path = os.path.join(DATA_DIR, f"{ticker}_{filing_year}_10k.pdf")
    if os.path.exists(local_path):
        print(f"  [rag_agent] Using cached filing: {local_path}")
        return local_path, filing_year

    print(f"  [rag_agent] Downloading from {doc_url}...")
    try:
        resp = requests.get(doc_url, headers=EDGAR_HEADERS, timeout=60, stream=True)
        resp.raise_for_status()

        # If the primary document is HTML (common for newer filings), try to get PDF version
        content_type = resp.headers.get("Content-Type", "")
        if "html" in content_type:
            # For HTML filings, we'll save as-is and use PyPDFLoader's fallback
            # A future enhancement could convert HTML → PDF via pdfkit
            print(f"  [rag_agent] Filing is HTML format, saving for text extraction...")
            local_path = os.path.join(DATA_DIR, f"{ticker}_{filing_year}_10k.htm")

        with open(local_path, "wb") as f:
            for chunk in resp.iter_content(chunk_size=8192):
                f.write(chunk)

        print(f"  [rag_agent] Downloaded: {local_path}")
        return local_path, filing_year

    except Exception as e:
        print(f"  [rag_agent] Download failed: {e}")
        return None, None


# ─── Chunking & Embedding ──────────────────────────────────────────────────────

def _load_and_chunk(file_path: str) -> list:
    """Load the 10-K file and split into chunks."""
    if file_path.endswith(".htm") or file_path.endswith(".html"):
        # Use LangChain's HTML loader for HTML filings
        from langchain_community.document_loaders import UnstructuredHTMLLoader
        loader = UnstructuredHTMLLoader(file_path)
    else:
        loader = PyPDFLoader(file_path)

    documents = loader.load()
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP,
        separators=["\n\n", "\n", " ", ""],
    )
    chunks = splitter.split_documents(documents)
    return chunks


def _build_vector_store(chunks: list, session_id: str) -> chromadb.Collection:
    """
    Embed chunks with sentence-transformers and store in ephemeral ChromaDB.
    Each session gets its own collection — no cross-session contamination.
    """
    client = chromadb.Client(Settings(anonymized_telemetry=False))
    collection_name = f"argus_{session_id}"
    collection = client.create_collection(collection_name)

    texts = [c.page_content for c in chunks]
    metadatas = [
        {
            "page": c.metadata.get("page", 0),
            "source": c.metadata.get("source", ""),
        }
        for c in chunks
    ]
    ids = [f"chunk_{i}" for i in range(len(texts))]

    # Embed in batches to avoid memory issues with large filings
    batch_size = 64
    all_embeddings = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i : i + batch_size]
        embeddings = _embedder.encode(batch, show_progress_bar=False).tolist()
        all_embeddings.extend(embeddings)

    collection.add(
        documents=texts,
        embeddings=all_embeddings,
        metadatas=metadatas,
        ids=ids,
    )
    return collection


# ─── RAG Answering ─────────────────────────────────────────────────────────────

def _answer_question(
    question: str,
    collection: chromadb.Collection,
    ticker: str,
    filing_year: str,
) -> RAGAnswer:
    """
    Retrieve relevant chunks for a question and generate an answer via Gemini.
    """
    # Embed the question
    q_embedding = _embedder.encode([question], show_progress_bar=False).tolist()[0]

    # Retrieve top-k chunks
    results = collection.query(
        query_embeddings=[q_embedding],
        n_results=RAG_TOP_K,
    )

    retrieved_texts = results["documents"][0]
    retrieved_pages = [m.get("page", 0) for m in results["metadatas"][0]]
    best_page = retrieved_pages[0] if retrieved_pages else 0

    context = "\n\n---\n\n".join(retrieved_texts)

    prompt = f"""
You are a financial analyst reviewing {ticker}'s {filing_year} 10-K SEC filing.

Based ONLY on the following excerpts from the filing, answer the question concisely.
If the information is not present in the excerpts, say "Not found in the provided filing excerpts."
Do not fabricate information.

FILING EXCERPTS:
{context}

QUESTION: {question}

Respond with a JSON object in exactly this format (no markdown, no extra text):
{{
  "answer": "<concise answer based only on the filing excerpts>",
  "confidence": <float 0.0-1.0 indicating how well the excerpts address the question>,
  "key_quote": "<a brief direct quote from the excerpts that best supports your answer, or empty string if none>"
}}
"""

    model = genai.GenerativeModel(
        GEMINI_MODEL,
        generation_config={"temperature": 0.1},
    )
    response = model.generate_content(prompt)
    raw = response.text.strip()

    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()

    try:
        parsed = json.loads(raw)
        return RAGAnswer(
            question=question,
            answer=parsed.get("answer", ""),
            source_page=best_page,
            confidence=float(parsed.get("confidence", 0.5)),
        )
    except json.JSONDecodeError:
        return RAGAnswer(
            question=question,
            answer=raw,
            source_page=best_page,
            confidence=0.4,
        )


# ─── Main Entry Point ──────────────────────────────────────────────────────────

def run(session: ResearchSession):
    """
    Main entry point called by the orchestrator.
    Downloads 10-K, builds vector store, answers all questions in session.filing_questions.
    """
    if not session.filing_questions:
        session.escalation_flags.append("rag_agent: no questions provided by orchestrator")
        return

    # Step 1: Download
    file_path, filing_year = _download_10k(session.ticker)
    if not file_path:
        session.escalation_flags.append(
            f"rag_agent: could not download 10-K for {session.ticker}"
        )
        return

    session.filing_path = file_path
    session.filing_year = filing_year or "unknown"

    # Step 2: Chunk and embed
    print(f"  [rag_agent] Chunking and embedding {session.ticker} {session.filing_year} 10-K...")
    chunks = _load_and_chunk(file_path)
    print(f"  [rag_agent] {len(chunks)} chunks created. Building vector store...")
    collection = _build_vector_store(chunks, session.session_id)

    # Step 3: Answer each question
    print(f"  [rag_agent] Answering {len(session.filing_questions)} questions...")
    answers = []
    for i, question in enumerate(session.filing_questions, 1):
        print(f"  [rag_agent] Q{i}: {question[:60]}...")
        answer = _answer_question(question, collection, session.ticker, session.filing_year)
        answers.append(answer)
        time.sleep(0.5)  # Brief pause to avoid Gemini rate limiting

    session.rag_answers = answers
    print(f"  [rag_agent] Done. Answered {len(answers)} questions.")
