"""
core/session.py
---------------
ResearchSession is the shared context object passed through the entire Argus pipeline.
Every agent reads from it and writes to it. The orchestrator mediates all access.
No agent calls another agent directly — they communicate through this object.
"""

from dataclasses import dataclass, field
from datetime import datetime
import uuid


@dataclass
class RAGAnswer:
    """Structured answer returned by the RAG agent for a single question."""
    question: str
    answer: str
    source_page: int
    confidence: float


@dataclass
class AuditEntry:
    """Single entry in the audit trail."""
    timestamp: str
    agent: str
    task_assigned: str
    orchestrator_reasoning: str
    output_summary: str
    latency_ms: int
    escalated: bool
    escalation_reason: str = ""


@dataclass
class ResearchSession:
    """
    Single source of truth for an Argus research run.
    Instantiated by the orchestrator, passed to every agent.
    """

    # --- Identity ---
    session_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    ticker: str = ""
    user_query: str = ""
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

    # --- Orchestrator planning ---
    research_plan: list[str] = field(default_factory=list)
    orchestrator_reasoning: str = ""

    # --- Sentiment Agent outputs ---
    sentiment_summary: str = ""
    sentiment_score: str = ""           # "positive" | "negative" | "mixed" | "neutral"
    sentiment_themes: list[str] = field(default_factory=list)
    sentiment_confidence: float = 0.0
    sentiment_sources: list[str] = field(default_factory=list)

    # --- Market Agent outputs ---
    # date range is SET BY ORCHESTRATOR based on sentiment, not hardcoded
    date_range_start: str = ""
    date_range_end: str = ""
    chart_path: str = ""
    price_trend: str = ""               # "uptrend" | "downtrend" | "sideways"
    price_change_pct: float = 0.0

    # --- RAG Agent outputs ---
    filing_path: str = ""
    filing_year: str = ""
    # questions are GENERATED BY ORCHESTRATOR based on sentiment themes
    filing_questions: list[str] = field(default_factory=list)
    rag_answers: list[RAGAnswer] = field(default_factory=list)

    # --- Orchestrator synthesis ---
    final_answer: str = ""
    risk_flags: list[str] = field(default_factory=list)
    confidence_overall: float = 0.0
    follow_up_questions: list[str] = field(default_factory=list)

    # --- Escalation ---
    escalation_flags: list[str] = field(default_factory=list)

    # --- Audit trail ---
    audit_trail: list[AuditEntry] = field(default_factory=list)

    def to_dict(self) -> dict:
        """Serialize session to dict for logging and Streamlit display."""
        return {
            "session_id": self.session_id,
            "ticker": self.ticker,
            "user_query": self.user_query,
            "created_at": self.created_at,
            "research_plan": self.research_plan,
            "sentiment": {
                "score": self.sentiment_score,
                "confidence": self.sentiment_confidence,
                "themes": self.sentiment_themes,
                "summary": self.sentiment_summary,
            },
            "market": {
                "date_range_start": self.date_range_start,
                "date_range_end": self.date_range_end,
                "price_trend": self.price_trend,
                "price_change_pct": self.price_change_pct,
                "chart_path": self.chart_path,
            },
            "rag": {
                "filing_path": self.filing_path,
                "filing_year": self.filing_year,
                "questions": self.filing_questions,
                "answers": [
                    {
                        "question": a.question,
                        "answer": a.answer,
                        "source_page": a.source_page,
                        "confidence": a.confidence,
                    }
                    for a in self.rag_answers
                ],
            },
            "synthesis": {
                "final_answer": self.final_answer,
                "risk_flags": self.risk_flags,
                "confidence_overall": self.confidence_overall,
                "follow_up_questions": self.follow_up_questions,
            },
            "audit_trail": [
                {
                    "timestamp": e.timestamp,
                    "agent": e.agent,
                    "task_assigned": e.task_assigned,
                    "orchestrator_reasoning": e.orchestrator_reasoning,
                    "output_summary": e.output_summary,
                    "latency_ms": e.latency_ms,
                    "escalated": e.escalated,
                    "escalation_reason": e.escalation_reason,
                }
                for e in self.audit_trail
            ],
        }
